# Generated by Django 4.2.13 on 2024-06-13 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'categoriAlmacen',
                'db_table': 'categoriAlmacen',
            },
        ),
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'categoriaProducto',
                'db_table': 'categoriaProducto',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numrastreo', models.CharField(default='', max_length=100)),
                ('fecha_compra', models.DateField(blank=True, max_length=2000, null=True)),
                ('identificado', models.BooleanField(default=False)),
                ('tienda_procedente', models.DateField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'paquete',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, max_length=100, null=True)),
                ('nro_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paqueteria.categoriaproducto')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paqueteria.paquete')),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='paqueteria.usuario'),
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('categoria_almaceb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paqueteria.categorialmacen')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
            },
        ),
    ]
