# Generated by Django 4.2.13 on 2024-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paqueteria', '0002_usuario_first_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='identificado',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default='2'),
        ),
    ]
