# Generated by Django 4.2.13 on 2024-06-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paqueteria', '0003_alter_paquete_identificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
