# Generated by Django 4.2.13 on 2024-06-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paqueteria', '0006_paquete_almacen_paquete_clasificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoriaProducto',
            new_name='categprod',
        ),
    ]
