# Generated by Django 4.2.13 on 2024-06-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paqueteria', '0007_rename_categoriaproducto_productos_categprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
