# Generated by Django 4.2.13 on 2024-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paqueteria', '0008_alter_paquete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorialmacen',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
